# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.srcs/sources_1/ip/ila_spi/ila_spi.xci
# IP: The module: 'ila_spi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/ila_spi/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_spi'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/ila_spi/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/ila_spi/ila_spi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.srcs/sources_1/ip/ila_spi/ila_spi.xci
# IP: The module: 'ila_spi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/ila_spi/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/ila_spi/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/ila_spi/ila_spi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_spi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
