# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.srcs/sources_1/ip/ila_uart_hello/ila_uart_hello.xci
# IP: The module: 'ila_uart_hello' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.gen/sources_1/ip/ila_uart_hello/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart_hello'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.gen/sources_1/ip/ila_uart_hello/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart_hello'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.gen/sources_1/ip/ila_uart_hello/ila_uart_hello_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart_hello'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.srcs/sources_1/ip/ila_uart_hello/ila_uart_hello.xci
# IP: The module: 'ila_uart_hello' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.gen/sources_1/ip/ila_uart_hello/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart_hello'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.gen/sources_1/ip/ila_uart_hello/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart_hello'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/Homework/Homework/uart_hello/uart_hello/uart_hello.gen/sources_1/ip/ila_uart_hello/ila_uart_hello_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_uart_hello'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
