# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.srcs/sources_1/ip/mmcm_100MHz/mmcm_100MHz.xci
# IP: The module: 'mmcm_100MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/mmcm_100MHz/mmcm_100MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_100MHz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/mmcm_100MHz/mmcm_100MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_100MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/mmcm_100MHz/mmcm_100MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_100MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.srcs/sources_1/ip/mmcm_100MHz/mmcm_100MHz.xci
# IP: The module: 'mmcm_100MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/mmcm_100MHz/mmcm_100MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_100MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/mmcm_100MHz/mmcm_100MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_100MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Rp/Desktop/digital_project/Protocol/project_1/project_1.gen/sources_1/ip/mmcm_100MHz/mmcm_100MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mmcm_100MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
